### PR TITLE
Add capability to utilize a custom repository file

### PR DESCRIPTION
**Pull request by lbgracioso**
This pull request introduces the capability to utilize a custom repository file and it also eliminates the GPG keys creation (Instead, it now utilizes a URL for this purpose).

Please note that the URL may be subject to modification in the future.

### CODE REVIEW

**Comment by viniciusferrao** [comment]
@lbgracioso why did you remove the capability of local files? That would prevent offline installations. Is there any reason or any fallback method to keep the offline install working?

**Comment by lbgracioso** [comment]
There was no "offline install" working, even before. It was only creating the GPG Keys.

The offline installation was a plan but not on my focus right now, and the code was also pretty messy. It's an idea to the future.

**Comment by lbgracioso** [comment]
@viniciusferrao Please see https://github.com/viniciusferrao/cloysterhpc/pull/53/commits/585aeea8e8e37261d54a6e804dfa0f150583ad9d

**Comment by viniciusferrao** [comment]
Thanks @lbgracioso

Theres some changes to do in the future but it's looks good.

**Pull request merged**
