### PR TITLE
Implement NVIDIA HPC SDK

### PR DESCRIPTION
**Pull request by lbgracioso**
This is just a first idea, a draft.

I'd like to know what we need to do with the NVIDIA HPC SDK to be able to integrate everything.

And I'm also waiting for the draft https://github.com/viniciusferrao/cloysterhpc/pull/53 to be reviewed and approved so I can integrate the repo in a more organized way.

### CODE REVIEW

**Comment by viniciusferrao** [comment]
I would avoid the class. Just use the repos mechanism instead? Be cause this way we have control to which repository we should use.

**Comment by lbgracioso** [comment]
@viniciusferrao What do you mean by "use the repos mechanism"? To install the `nvhpc` package?

**Comment by lbgracioso** [comment]
With the approval of the PR for the use of local repository, the `gpgkeys.h` and `gpgtools.h` headers are added. I'm going to add the repository now and send a commit.

**Comment by viniciusferrao** [comment]
> @viniciusferrao What do you mean by "use the repos mechanism"? To install the `nvhpc` package?

If I'm not wrong the package if just some repos for `/etc/yum.repos.d/` and GPG keys. If that's really the case is just a repository.

**Comment by lbgracioso** [comment]
I don't think it would be a good idea... I think it's better to make the separation between `tool` and `repo` clear.

If the `repo` classes start installing the `tools`, better to redefine the `repo` class to another name and its functionalities too... I prefer it separately, more **specific**.

**Review by viniciusferrao — APPROVED** [review]

**Comment by viniciusferrao** [comment]
> I don't think it would be a good idea... I think it's better to make the separation between `tool` and `repo` clear.
> 
> If the `repo` classes start installing the `tools`, better to redefine the `repo` class to another name and its functionalities too... I prefer it separately, more **specific**.

I got what you mean. You explicit mean the installation of the package and I was questioning the way to add to repository to the system.

I will approve it as is. Not sure exactly but seems good enough for now.

**Pull request merged**
