### PR TITLE
[CLOYSTER-116] Implement Ansible + Vagrant to run Cloyster

### PR DESCRIPTION
**Pull request by lbgracioso**
This PR transitions Vagrant management to Ansible.

- **Improved Code Quality**: Now we have a cleaner and more maintainable code.
- **Enhanced Maintainability**: Reduces redundancy by eliminating repetitive tasks.
- **Increased Automation**: More efficient provisioning with less intervention as possible.

### CODE REVIEW

**Comment by viniciusferrao** [comment]
There's a lot of 'shell' use when calling vagrant. There's a way to avoid it?

**Comment by lbgracioso** [comment]
What do you mean with "when calling Vagrant" @viniciusferrao? The Vagrant commands (_up, scp, ssh_)?

**Comment by lbgracioso** [comment]
I really can't see the problem @viniciusferrao, these are native commands from Vagrant. Why would I avoid them?

**Comment by viniciusferrao** [comment]
> I really can't see the problem @viniciusferrao, these are native commands from Vagrant. Why would I avoid them?
> 
> Plus, the only areas where I'm using shell are the ones where Vagrant can't do the job alone. For example, where I add a new disk I could use a plugin called _vagrant-disksize_ but it has many compatibility problems.

It's because `shell` is usually the last resort that you should use. Only if there's no native module.

Look here: https://www.reddit.com/r/ansible/comments/pyq3cb/can_you_clearly_articulate_why_using_ansible_to/

If there's no other way OK, but if there's a native module for Vagrant that should be used.

**Pull request merged**
